version = 0.1

[dev.deploy.parameters]
stack_name = "tickets-api-dev"
resolve_s3 = true
s3_prefix = "tickets-api-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []

[dev.global.parameters]
region = "us-east-1"
